apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/init-test:6
---
apiVersion: v1
kind: Service
metadata:
  name: sb-svc
spec:
  type: ClusterIP
  selector:
    app: spring
  ports:
  - port: 8085
    targetPort: 8085
